/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3cfp27;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author Katsuo
 */
public class AplicacionCFP27 extends javax.swing.JFrame {

    private static final String PANEL_USUARIO = "Panel usuario";
    private static final String PANEL_INGRESO = "Panel ingreso";

    private static final String DEF_CONTRASENIA = "def contraseña";
    private static final String DEF_USUARIO = "Usuario";

    private static final String DEF_USUARIO_VACIO = "";
    private static final String DEF_CONTRASENIA_VACIO = "";
    
    private static final boolean CONFIG_TAM_DEF_APP = false;
    
    private static final boolean MSJ_VISIBILIIDAD_DEF_ERROR = false;
    private static final boolean MSJ_ERROR_NO_GENERADO = false;
    private static final boolean MSJ_ERROR_GENERADO = true;
    
    private static final Component POSICION_CENTRO_DEF = null;

    private CardLayout controladorVentanas;

    private ConexionDB conexionCfp27;

    private int cantidadIntentos;

    /**
     * Creates new form AplicacionCFP27
     */
    public AplicacionCFP27() {
        initComponents();

        conexionCfp27 = new ConexionDB();

        jPasswordFieldContrasenia.setText(DEF_CONTRASENIA);
        jTextFieldUsuario.setText(DEF_USUARIO);

        controladorVentanas = new CardLayout();

        jPanelPrincipal.setLayout(controladorVentanas);//asignado el contralor de ventanas al panel principal
        jPanelPrincipal.add(jPanelIngreso, PANEL_INGRESO);//agrega el panel ingreso al panel principal para guardar
        jPanelPrincipal.add(jPanelUsuario, PANEL_USUARIO);//agrega el panel usuario al panel principal para guardar

        configuracionPanelPrincipal(PANEL_INGRESO, jPanelIngreso.getPreferredSize());

        this.setResizable(CONFIG_TAM_DEF_APP);//evita que la ventana se pueda modificar de tamaño

        jLabelErrorIngreso.setVisible(MSJ_VISIBILIIDAD_DEF_ERROR);//al inicar la aplicacion este componente no sera visible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIngreso = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();
        jLabelErrorIngreso = new javax.swing.JLabel();
        jPanelUsuario = new javax.swing.JPanel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPromedio = new javax.swing.JTextField();
        jPanelPrincipal = new javax.swing.JPanel();

        jButtonIngresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseClicked(evt);
            }
        });

        jTextFieldUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUsuario.setText("jTextField1");
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });

        jPasswordFieldContrasenia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordFieldContrasenia.setText("como estan ? ");
        jPasswordFieldContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseniaFocusLost(evt);
            }
        });

        jLabelErrorIngreso.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelErrorIngreso.setForeground(new java.awt.Color(255, 51, 102));
        jLabelErrorIngreso.setText("Error, usuario y/o contraseña incorrectos");

        javax.swing.GroupLayout jPanelIngresoLayout = new javax.swing.GroupLayout(jPanelIngreso);
        jPanelIngreso.setLayout(jPanelIngresoLayout);
        jPanelIngresoLayout.setHorizontalGroup(
            jPanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresoLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButtonIngresar)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIngresoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(jPanelIngresoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelErrorIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIngresoLayout.setVerticalGroup(
            jPanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPasswordFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButtonIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabelErrorIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jButtonCerrarSesion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar sesion");
        jButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseClicked(evt);
            }
        });

        jTextFieldEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldEmail.setText("Email");

        jTextFieldNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldNombre.setText("Nombre");

        jTextFieldPromedio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldPromedio.setText("Promedio: -");

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCerrarSesion)
                .addGap(24, 24, 24))
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(524, Short.MAX_VALUE))
            .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(620, Short.MAX_VALUE)))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap())
            .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseClicked
       if (conexionCfp27.verificarUsuarioRegistrado(jTextFieldUsuario.getText(),
                new String(jPasswordFieldContrasenia.getPassword()))) {
            jTextFieldUsuario.setText(DEF_USUARIO);//cambiar el texto del campo de usuario a "Usuario"
            jPasswordFieldContrasenia.setText(DEF_CONTRASENIA);//cambiar el texto de campo de contraseña a "def contraseña"
            configuracionPanelPrincipal(PANEL_USUARIO, jPanelUsuario.getPreferredSize());//cambio al panel de usuario
            jLabelErrorIngreso.setVisible(MSJ_ERROR_NO_GENERADO);//oculto el mensaje del error una vez que el usuario logro ingresar
            
            Estudiante auxEstudiante = conexionCfp27.getEstudianteVerificado();//guardo info del estudiante verificado en auxEstudiante
                                                                               // para no acceder todo el tiempo con conexionCfp27
            jTextFieldNombre.setText(auxEstudiante.getNombre());       
            jTextFieldEmail.setText(auxEstudiante.getEmail());
            
            float promedio = 0;            
            for(int nota : auxEstudiante.getNotas()){                
                promedio += nota;
            }
            jTextFieldPromedio.setText("Promedio: "+ promedio/Estudiante.MAX_NOTAS);
            
        } else {
            jLabelErrorIngreso.setVisible(MSJ_ERROR_GENERADO);//codigo para que se muestre el mensaje del error
        }
    }//GEN-LAST:event_jButtonIngresarMouseClicked

    private void jButtonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseClicked
        configuracionPanelPrincipal(PANEL_INGRESO, jPanelIngreso.getPreferredSize());//cambio al panel de ingreso
    }//GEN-LAST:event_jButtonCerrarSesionMouseClicked

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        // TODO add your handling code here:
        if (jTextFieldUsuario.getText().equals(DEF_USUARIO)) {
            jTextFieldUsuario.setText(DEF_USUARIO_VACIO);
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        if (jTextFieldUsuario.getText().equals(DEF_USUARIO_VACIO)) {
            jTextFieldUsuario.setText(DEF_USUARIO);
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordFieldContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseniaFocusGained
        if (new String(jPasswordFieldContrasenia.getPassword()).equals(DEF_CONTRASENIA)) {
            jPasswordFieldContrasenia.setText(DEF_CONTRASENIA_VACIO);
        }
    }//GEN-LAST:event_jPasswordFieldContraseniaFocusGained

    private void jPasswordFieldContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseniaFocusLost
        if (new String(jPasswordFieldContrasenia.getPassword()).equals(DEF_CONTRASENIA_VACIO)) {
            jPasswordFieldContrasenia.setText(DEF_CONTRASENIA);
        }
    }//GEN-LAST:event_jPasswordFieldContraseniaFocusLost

    /**
     * Configura el panel principal. Modifica el tamanio al panel a mostrar y la
     * posicion al centro de la pantalla
     *
     * @param nombrePanel nombre del panel a mostrar
     * @param tamanioPanel tamanio del panel a mostrar
     */
    private void configuracionPanelPrincipal(String nombrePanel, Dimension tamanioPanel) {
        controladorVentanas.show(jPanelPrincipal, nombrePanel);
        jPanelPrincipal.setPreferredSize(tamanioPanel);
        this.pack();//asigna el tamaño de ventana correspondiente al panel asignado
        this.setLocationRelativeTo(POSICION_CENTRO_DEF);//inicializa la ventana en el centro de la pantalla
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionCFP27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionCFP27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionCFP27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionCFP27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacionCFP27().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabelErrorIngreso;
    private javax.swing.JPanel jPanelIngreso;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPromedio;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
